### ISSUE TITLE
IntelliJ Silent update is not working

### ISSUE THREAD

**Issue by nerjamartin** [appget/appget#33]
Hi there, and thanks for AppGet.
I'm giving it a try and so far I'm very pleased. Good job!

Nevertheless I'm trying to update IntelliJ Community Edition (from 182.4892.20 to 183.5912.21).

I have an error during installation (Silent Mode)

![image](https://user-images.githubusercontent.com/7492281/55042312-37206400-5031-11e9-9eb7-7e97937ca315.png)

In the logs : 

```
2019-03-27 01:40:27.2670 8816:8 [Fatal]  UpdateService: An error occurred while updating intellijAppGet.Installers.InstallerException: Installer for IntelliJ IDEA Community 183.5912.21 returned with a non-zero exit code: 2. Installation aborted by script
   at AppGet.Installers.InstallService.RunInstaller(InstallInteractivityLevel interactivity, PackageManifest packageManifest, IInstaller whisperer) in c:\src\src\AppGet\Installers\InstallService.cs:line 163
   at AppGet.Installers.InstallService.<Install>d__12.MoveNext() in c:\src\src\AppGet\Installers\InstallService.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AppGet.Update.UpdateService.<UpdatePackage>d__8.MoveNext() in c:\src\src\AppGet\Update\UpdateService.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AppGet.Update.UpdateService.<UpdateAllPackages>d__9.MoveNext() in c:\src\src\AppGet\Update\UpdateService.cs:line 78
```

**Comment by kayone** [comment]
I'm glad you find appget useful, this is a known issue #31 I'll see if I can do a beta release of it sometime this week.

I'm gonna close this issue in favour of #31
